var roadAtlasStyles=[{featureType:"all",elementType:"all",stylers:[{saturation:-80},{lightness:-40},{gamma:0.6}]},{featureType:"water",elementType:"all",stylers:[{saturation:0},{lightness:70}]}],layer,tableid=552892,tableid2=874780,zoom=3,latlng=new google.maps.LatLng(37,-5.6),suggestion,ne,sw,tabkey,regex1,query="";
$("#search").live("keydown",function(a){if(9==(a.keyCode||a.which))a.preventDefault(),suggestion&&(regex1=RegExp("^"+$("#search").val()+"(.*?)( |$)","ig"),tabkey=suggestion.match(regex1),$("#search").val(tabkey))});
function initialize(){getParams();map=new google.maps.Map(document.getElementById("map_canvas"),{center:latlng,zoom:zoom,minZoom:2,mapTypeControl:!0,mapTypeControlOptions:{style:google.maps.MapTypeControlStyle.DEFAULT,mapTypeIds:[google.maps.MapTypeId.SATELLITE,"usroadatlas"],position:google.maps.ControlPosition.TOP_RIGHT},scrollwheel:!0,navigationControl:!0,navigationControlOptions:{style:google.maps.NavigationControlStyle.SMALL,position:google.maps.ControlPosition.TOP_RIGHT}});var a=new google.maps.StyledMapType(roadAtlasStyles,
{name:"Newspaper Map"});map.mapTypes.set("usroadatlas",a);map.setMapTypeId("usroadatlas");google.maps.event.addListener(map,"center_changed",function(){updateHash()});google.maps.event.addListener(map,"zoom_changed",function(){updateHash()});geocoder=new google.maps.Geocoder;layer=new google.maps.FusionTablesLayer(tableid);query&&layer.setQuery(query);layer.setMap(map);$("#search").keyup(primaryFunction);$("#search").submit(primaryFunction);a=document.createElement("DIV");new Legend(a,map);a.index=
1;map.controls[google.maps.ControlPosition.RIGHT_BOTTOM].push(a)}
function Legend(a){a.style.padding="7px";var b=document.createElement("DIV");b.style.background='rgba(0,0,0,0.8) url("bg.png") 0 0 no-repeat';b.style.borderRadius="3px";b.title="newspaper map in other languages";a.appendChild(b);a=document.createElement("DIV");a.style.fontFamily="Arial,sans-serif";a.style.color="#fff";a.style.fontSize="10px";a.style.paddingLeft="20px";a.style.paddingRight="3px";a.style.paddingTop="10px";a.innerHTML='English<br/><a title="newsapp.es" href="http://newspapermap.com/ES.html"> Spanish | Espa\u00f1ol</a><br/><a title="plan de journaux" href="http://newspapermap.com/FR.html"> French | Fran\u00e7aise</a><br/><a title="mapa do jornais" href="http://newspapermap.com/PT.html"> Portuguese | Portugu\u00eas</a><br/><a title="zeitungskarte.de" href="http://zeitungskarte.de"> German | Deutsch</a><br/><a  title="\u0413\u0430\u0437\u0435\u0442\u0430 \u043a\u0430\u0440\u0442\u0430" href="http://newspapermap.com/RU.html"> Russian | P\u0443\u0441\u0441\u043a\u0438\u0439</a><br/> <a  title="newsapp.jp" href="http://newspapermap.com/JA.html"> Japanese | \u65e5\u672c</a><br/><a  title="\u0635\u062d\u064a\u0641\u0629 \u0627\u0644\u062e\u0631\u064a\u0637\u0629" href="http://newspapermap.com/AR.html"> Arabic | \u0627\u0644\u0639\u0631\u0628\u064a\u0629</a><br/><a  title="\uc2e0\ubb38\uc9c0\ub3c4" href="http://newspapermap.com/KO.html"> Korean | \ud55c\uad6d\uc758</a><br/>Other<br/>';
b.appendChild(a)}function changeData(a){a=encodeURIComponent("SELECT Name, Lat, Long FROM "+tableid+" WHERE Name CONTAINS IGNORING CASE '"+a+"'");(new google.visualization.Query("http://www.google.com/fusiontables/gvizdata?tq="+a)).send(getData)}
function getData(a){fname=a.getDataTable().getValue(0,0);lat=a.getDataTable().getValue(0,1);lon=a.getDataTable().getValue(0,2);map.setZoom(19);map.setCenter(new google.maps.LatLng(lat,lon));layer.setQuery("SELECT lat_long FROM "+tableid+" WHERE Name CONTAINS '"+fname+"'");layer.setMap(map);layer2.setMap(null)}function changeMap0(){lang=document.getElementById("lang").value;layer.setQuery("SELECT lat_long FROM "+tableid+" WHERE language CONTAINS '"+lang+"'");layer.setMap(map);layer2.setMap(null)}
function changeMap10(){filter=document.getElementById("filter").value;layer.setQuery("SELECT lat_long FROM "+tableid+" WHERE '"+filter+"' = '"+filter+"'");layer.setMap(map);layer2.setMap(null)}function changeMap6(){layer.setQuery("SELECT lat_long FROM  "+tableid+"");layer.setMap(map);layer2.setMap(null)}function changeMap7(){layer.setQuery("SELECT lat_long FROM "+tableid+" WHERE large = 'large'");layer.setMap(map);layer2.setMap(null)}
function changeMap8(){layer.setMap(null);layer2=new google.maps.FusionTablesLayer(tableid2);layer2.setMap(map)}function primaryFunction(){$("#search").val();$.ajax({type:"GET",url:"http://maps-api-ssl.google.com/maps/suggest?hl=en&gl=en&v=3.6&json=b&auth=ABQIAAAAALakLdjjlTHt7ZswQah3VRQhzk0B9PQtvkZRIRmh2TMWxDe2yRSKq5BP3oJYSnI5FTbfuS_Rdg8dEQ&src=1,2&num=5&numps=5&callback=handleResponse&q="+$("#search").val()+"&cp="+$("#search").val().length,dataType:"script",queue:"SUG1",cancelExisting:!0})}
handleResponse={};handleResponse=function(a){DIR1b4=suggestion;DIR1now=suggestion=parse(a);DIR1b4!=DIR1now&&(updateHTML("suggestion",suggestion),codeAddress(suggestion))};function updateHTML(a,b){document.getElementById(a).innerHTML=b}function parse(a){return a.suggestion[0].query?a.suggestion[0].query:null}
function codeAddress(a){geocoder.geocode({address:a},function(a,c){if(c==google.maps.GeocoderStatus.OK){var f=a[0].geometry.viewport.getNorthEast(),e=a[0].geometry.viewport.getSouthWest();map.fitBounds(a[0].geometry.viewport);layer.setQuery("SELECT lat_long FROM  "+tableid+"");layer.setMap(map);layer2.setMap(null);new google.maps.LatLng(f.lat(),e.lng());new google.maps.LatLng(e.lat(),f.lng())}})}
function updateHash(){var a=map.getCenter().lat(),b=map.getCenter().lng(),c=map.getZoom();window.location.hash="slat="+a+"&slong="+b+"&zoom="+c}function getParams(){var a=window.location.hash;""!=a&&(params=a.split("&"),slat=params[0].split("=")[1],slong=params[1].split("=")[1],latlng=new google.maps.LatLng(slat,slong),zoom=parseInt(params[2].split("=")[1]))}
(function(a){a.fn.extend({autocomplete:function(b,c){var f="string"==typeof b,c=a.extend({},a.Autocompleter.defaults,{url:f?b:null,data:f?null:b,delay:f?a.Autocompleter.defaults.delay:10,max:c&&!c.scroll?100:150},c);c.highlight=c.highlight||function(a){return a};c.formatMatch=c.formatMatch||c.formatItem;return this.each(function(){new a.Autocompleter(this,c)})},result:function(a){return this.bind("result",a)},search:function(a){return this.trigger("search",[a])},flushCache:function(){return this.trigger("flushCache")},
setOptions:function(a){return this.trigger("setOptions",[a])},unautocomplete:function(){return this.trigger("unautocomplete")}});a.Autocompleter=function(b,c){function f(){var s=k.selected();if(!s)return!1;var d=s.result;m=d;if(c.multiple){var g=q(i.val());if(1<g.length){var e=c.multipleSeparator.length,h=a(b).selection().start,o,f=0;a.each(g,function(a,b){f+=b.length;if(h<=f)return o=a,!1;f+=e});g[o]=d;d=g.join(c.multipleSeparator)}d+=c.multipleSeparator}i.val(d);n();i.trigger("result",[s.data,s.value]);
return!0}function e(a,b){if(t==d)k.hide();else{var g=i.val();if(b||g!=m)m=g,g=j(g),g.length>=c.minChars?(i.addClass(c.loadingClass),c.matchCase||(g=g.toLowerCase()),h(g,o,n)):(i.removeClass(c.loadingClass),k.hide())}}function q(b){return!b?[""]:!c.multiple?[a.trim(b)]:a.map(b.split(c.multipleSeparator),function(c){return a.trim(b).length?a.trim(c):null})}function j(g){if(!c.multiple)return g;var d=q(g);if(1==d.length)return d[0];d=a(b).selection().start;d=d==g.length?q(g):q(g.replace(g.substring(d),
""));return d[d.length-1]}function n(){k.visible();k.hide();clearTimeout(r);i.removeClass(c.loadingClass);c.mustMatch&&i.search(function(a){a||(c.multiple?(a=q(i.val()).slice(0,-1),i.val(a.join(c.multipleSeparator)+(a.length?c.multipleSeparator:""))):(i.val(""),i.trigger("result",null)))})}function o(d,e){if(e&&e.length&&g){i.removeClass(c.loadingClass);k.display(e,d);var h=e[0].value;c.autoFill&&j(i.val()).toLowerCase()==d.toLowerCase()&&t!=p&&(i.val(i.val()+h.substring(j(m).length)),a(b).selection(m.length,
m.length+h.length));k.show()}else n()}function h(g,d,e){c.matchCase||(g=g.toLowerCase());var h=l.load(g);if(h&&h.length)d(g,h);else if("string"==typeof c.url&&0<c.url.length){var f={timestamp:+new Date};a.each(c.extraParams,function(a,b){f[a]="function"==typeof b?b():b});a.ajax({mode:"abort",port:"autocomplete"+b.name,dataType:c.dataType,url:c.url,data:a.extend({q:j(g),limit:c.max},f),success:function(b){var e;if(!(e=c.parse&&c.parse(b))){e=[];for(var b=b.split("\n"),h=0;h<b.length;h++){var f=a.trim(b[h]);
f&&(f=f.split("|"),e[e.length]={data:f,value:f[0],result:c.formatResult&&c.formatResult(f,f[0])||f[0]})}}l.add(g,e);d(g,e)}})}else k.emptyList(),e(g)}var d,p;d=46;p=8;var i=a(b).attr("autocomplete","off").addClass(c.inputClass),r,m="",l=a.Autocompleter.Cache(c),g=0,t,v={mouseDownOnSelect:!1},k=a.Autocompleter.Select(c,b,f,v),u;a.browser.opera&&a(b.form).bind("submit.autocomplete",function(){if(u)return u=!1});i.bind((a.browser.opera?"keypress":"keydown")+".autocomplete",function(b){g=1;t=b.keyCode;
switch(b.keyCode){case 38:b.preventDefault();k.visible()?k.prev():e(0,!0);break;case 40:b.preventDefault();k.visible()?k.next():e(0,!0);break;case 33:b.preventDefault();k.visible()?k.pageUp():e(0,!0);break;case 34:b.preventDefault();k.visible()?k.pageDown():e(0,!0);break;case c.multiple&&","==a.trim(c.multipleSeparator)&&188:case 9:case 13:if(f())return b.preventDefault(),u=!0,!1;break;case 27:k.hide();break;default:clearTimeout(r),r=setTimeout(e,c.delay)}}).focus(function(){g++}).blur(function(){g=
0;v.mouseDownOnSelect||(clearTimeout(r),r=setTimeout(n,200))}).click(function(){1<g++&&!k.visible()&&e(0,!0)}).bind("search",function(){function b(a,g){var d;if(g&&g.length)for(var e=0;e<g.length;e++)if(g[e].result.toLowerCase()==a.toLowerCase()){d=g[e];break}"function"==typeof c?c(d):i.trigger("result",d&&[d.data,d.value])}var c=1<arguments.length?arguments[1]:null;a.each(q(i.val()),function(a,c){h(c,b,b)})}).bind("flushCache",function(){l.flush()}).bind("setOptions",function(b,g){a.extend(c,g);
"data"in g&&l.populate()}).bind("unautocomplete",function(){k.unbind();i.unbind();a(b.form).unbind(".autocomplete")})};a.Autocompleter.defaults={inputClass:"ac_input",resultsClass:"ac_results",loadingClass:"ac_loading",minChars:1,delay:400,matchCase:!1,matchSubset:!0,matchContains:!1,cacheLength:10,max:100,mustMatch:!1,extraParams:{},selectFirst:!0,formatItem:function(a){return a[0]},formatMatch:null,autoFill:!1,width:0,multiple:!1,multipleSeparator:", ",highlight:function(a,c){return a.replace(RegExp("(?![^&;]+;)(?!<[^<>]*)("+
c.replace(/([\^\$\(\)\[\]\{\}\*\.\+\?\|\\])/gi,"\\$1")+")(?![^<>]*>)(?![^&;]+;)","gi"),"<strong>$1</strong>")},scroll:!0,scrollHeight:180};a.Autocompleter.Cache=function(b){function c(a,c){b.matchCase||(a=a.toLowerCase());var d=a.indexOf(c);"word"==b.matchContains&&(d=a.toLowerCase().search("\\b"+c.toLowerCase()));return-1==d?!1:0==d||b.matchContains}function f(a,c){n>b.cacheLength&&q();j[a]||n++;j[a]=c}function e(){if(!b.data)return!1;var c={},e=0;if(!b.url)b.cacheLength=1;c[""]=[];for(var d=0,n=
b.data.length;d<n;d++){var i=b.data[d],i="string"==typeof i?[i]:i,j=b.formatMatch(i,d+1,b.data.length);if(!1!==j){var m=j.charAt(0).toLowerCase();c[m]||(c[m]=[]);i={value:j,data:i,result:b.formatResult&&b.formatResult(i)||j};c[m].push(i);e++<b.max&&c[""].push(i)}}a.each(c,function(a,c){b.cacheLength++;f(a,c)})}function q(){j={};n=0}var j={},n=0;setTimeout(e,25);return{flush:q,add:f,populate:e,load:function(e){if(!b.cacheLength||!n)return null;if(!b.url&&b.matchContains){var f=[],d;for(d in j)if(0<
d.length){var p=j[d];a.each(p,function(a,b){c(b.value,e)&&f.push(b)})}return f}if(j[e])return j[e];if(b.matchSubset)for(d=e.length-1;d>=b.minChars;d--)if(p=j[e.substr(0,d)])return f=[],a.each(p,function(a,b){c(b.value,e)&&(f[f.length]=b)}),f;return null}}};a.Autocompleter.Select=function(b,c,f,e){function q(){r&&(m=a("<div/>").hide().addClass(b.resultsClass).css("position","absolute").appendTo(document.body),l=a("<ul/>").appendTo(m).mouseover(function(b){j(b).nodeName&&"LI"==j(b).nodeName.toUpperCase()&&
(d=a("li",l).removeClass(o).index(j(b)),a(j(b)).addClass(o))}).click(function(b){a(j(b)).addClass(o);f();c.focus();return!1}).mousedown(function(){e.mouseDownOnSelect=!0}).mouseup(function(){e.mouseDownOnSelect=!1}),0<b.width&&m.css("width",b.width),r=!1)}function j(a){for(a=a.target;a&&"LI"!=a.tagName;)a=a.parentNode;return!a?[]:a}function n(a){h.slice(d,d+1).removeClass(o);d+=a;0>d?d=h.size()-1:d>=h.size()&&(d=0);a=h.slice(d,d+1).addClass(o);if(b.scroll){var c=0;h.slice(0,d).each(function(){c+=
this.offsetHeight});c+a[0].offsetHeight-l.scrollTop()>l[0].clientHeight?l.scrollTop(c+a[0].offsetHeight-l.innerHeight()):c<l.scrollTop()&&l.scrollTop(c)}}var o;o="ac_over";var h,d=-1,p,i="",r=!0,m,l;return{display:function(c,e){q();p=c;i=e;l.empty();for(var f=b.max&&b.max<p.length?b.max:p.length,k=0;k<f;k++)if(p[k]){var j=b.formatItem(p[k].data,k+1,f,p[k].value,i);!1!==j&&(j=a("<li/>").html(b.highlight(j,i)).addClass(0==k%2?"ac_even":"ac_odd").appendTo(l)[0],a.data(j,"ac_data",p[k]))}h=l.find("li");
b.selectFirst&&(h.slice(0,1).addClass(o),d=0);a.fn.bgiframe&&l.bgiframe()},next:function(){n(1)},prev:function(){n(-1)},pageUp:function(){0!=d&&0>d-8?n(-d):n(-8)},pageDown:function(){d!=h.size()-1&&d+8>h.size()?n(h.size()-1-d):n(8)},hide:function(){m&&m.hide();h&&h.removeClass(o);d=-1},visible:function(){return m&&m.is(":visible")},current:function(){return this.visible()&&(h.filter("."+o)[0]||b.selectFirst&&h[0])},show:function(){var e=a(c).offset();m.css({width:"string"==typeof b.width||0<b.width?
b.width:a(c).width(),top:e.top+c.offsetHeight,left:e.left}).show();if(b.scroll&&(l.scrollTop(0),l.css({maxHeight:b.scrollHeight,overflow:"auto"}),a.browser.msie&&"undefined"===typeof document.body.style.maxHeight)){var d=0;h.each(function(){d+=this.offsetHeight});e=d>b.scrollHeight;l.css("height",e?b.scrollHeight:d);e||h.width(l.width()-parseInt(h.css("padding-left"))-parseInt(h.css("padding-right")))}},selected:function(){var b=h&&h.filter("."+o).removeClass(o);return b&&b.length&&a.data(b[0],"ac_data")},
emptyList:function(){l&&l.empty()},unbind:function(){m&&m.remove()}}};a.fn.selection=function(a,c){if(void 0!==a)return this.each(function(){if(this.createTextRange){var e=this.createTextRange();void 0===c||a==c?e.move("character",a):(e.collapse(!0),e.moveStart("character",a),e.moveEnd("character",c));e.select()}else if(this.setSelectionRange)this.setSelectionRange(a,c);else if(this.selectionStart)this.selectionStart=a,this.selectionEnd=c});var f=this[0];if(f.createTextRange){var e=document.selection.createRange(),
q=f.value,j=e.text.length;e.text="<->";e=f.value.indexOf("<->");f.value=q;this.selection(e,e+j);return{start:e,end:e+j}}if(void 0!==f.selectionStart)return{start:f.selectionStart,end:f.selectionEnd}}})(jQuery);jQuery.ajaxQueue=function(a){var b=a.complete;a.complete=function(){b&&b.apply(this,arguments);jQuery.dequeue(jQuery.ajaxQueue,"ajax")};jQuery([jQuery.ajaxQueue]).queue("ajax",function(){jQuery.ajax(a)})};
jQuery.ajaxSync=function(a){var b=jQuery.ajaxSync.fn,c=jQuery.ajaxSync.data,f=b.length;b[f]={error:a.error,success:a.success,complete:a.complete,done:!1};c[f]={error:[],success:[],complete:[]};a.error=function(){c[f].error=arguments};a.success=function(){c[f].success=arguments};a.complete=function(){c[f].complete=arguments;b[f].done=!0;if(0==f||!b[f-1])for(var a=f;a<b.length&&b[a].done;a++)b[a].error&&b[a].error.apply(jQuery,c[a].error),b[a].success&&b[a].success.apply(jQuery,c[a].success),b[a].complete&&
b[a].complete.apply(jQuery,c[a].complete),b[a]=null,c[a]=null};return jQuery.ajax(a)};jQuery.ajaxSync.fn=[];jQuery.ajaxSync.data=[];